services:
  kart-game:
    build: ./mario-kart-react
    container_name: mario-kart-container
    ports:
      - "5173:5173"
    volumes:
      - ./mario-kart-react:/app               # Sincronizza il tuo codice
      - /app/node_modules    # IMPORTANTE: Usa i node_modules interni al container
      - ./certs:/app/certs
    environment:
      - CHOKIDAR_USEPOLLING=true # Fix per aggiornamento automatico file

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: transcendence_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql # Salva i dati anche se spegni il container

  kart-server:
      build: ./backend
      container_name: nestjs-backend
      ports:
        - "3000:3000" # porta default per NestJs
      volumes:
        - ./backend:/app
        - /app/node_modules
        - ./certs:/app/certs
      depends_on:
      - db  # Fa partire prima il database, poi il backend
      environment:
        - NODE_ENV=development
        - DB_HOST=db
        - DB_PORT=3306
        - DB_USER=user
        - DB_PASS=user_password
        - DB_NAME=transcendence_db
      command: npm run start:dev

volumes:
  db_data: