/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/LUIGICIRCUIT.glb --shadows --keepnames 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/LUIGICIRCUIT.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.beginner_course} />
        <skinnedMesh name="polygon0" geometry={nodes.polygon0.geometry} material={materials.ef_dushBoard} skeleton={nodes.polygon0.skeleton} />
        <skinnedMesh name="polygon1" geometry={nodes.polygon1.geometry} material={materials.a_bc_enseki_m} skeleton={nodes.polygon1.skeleton} />
        <skinnedMesh name="polygon101" geometry={nodes.polygon101.geometry} material={materials.lugcap_m} skeleton={nodes.polygon101.skeleton} />
        <skinnedMesh name="polygon106" geometry={nodes.polygon106.geometry} material={materials.bc_spot_m} skeleton={nodes.polygon106.skeleton} />
        <skinnedMesh name="polygon116" geometry={nodes.polygon116.geometry} material={materials.lake_m} skeleton={nodes.polygon116.skeleton} />
        <skinnedMesh name="polygon117" geometry={nodes.polygon117.geometry} material={materials.yama_m} skeleton={nodes.polygon117.skeleton} />
        <skinnedMesh name="polygon17" geometry={nodes.polygon17.geometry} material={materials.bc_kankyaku_m} skeleton={nodes.polygon17.skeleton} />
        <skinnedMesh name="polygon1b" geometry={nodes.polygon1b.geometry} material={materials.shadow} skeleton={nodes.polygon1b.skeleton} />
        <skinnedMesh name="polygon2" geometry={nodes.polygon2.geometry} material={materials.a_kusa_soto} skeleton={nodes.polygon2.skeleton} />
        <skinnedMesh name="polygon20" geometry={nodes.polygon20.geometry} material={materials.fence} skeleton={nodes.polygon20.skeleton} />
        <skinnedMesh name="polygon22" geometry={nodes.polygon22.geometry} material={materials.popkanban_m} skeleton={nodes.polygon22.skeleton} />
        <skinnedMesh name="polygon23" geometry={nodes.polygon23.geometry} material={materials.kusa_kanban_m} skeleton={nodes.polygon23.skeleton} />
        <skinnedMesh name="polygon27" geometry={nodes.polygon27.geometry} material={materials.a_bc_kankyakuseat_m} skeleton={nodes.polygon27.skeleton} />
        <skinnedMesh name="polygon27b" geometry={nodes.polygon27b.geometry} material={materials.shadow} skeleton={nodes.polygon27b.skeleton} />
        <skinnedMesh name="polygon2b" geometry={nodes.polygon2b.geometry} material={materials.shadow} skeleton={nodes.polygon2b.skeleton} />
        <skinnedMesh name="polygon3" geometry={nodes.polygon3.geometry} material={materials.a_kusa_waki_m} skeleton={nodes.polygon3.skeleton} />
        <skinnedMesh name="polygon38" geometry={nodes.polygon38.geometry} material={materials.enkei_yama_m} skeleton={nodes.polygon38.skeleton} />
        <skinnedMesh name="polygon39" geometry={nodes.polygon39.geometry} material={materials.kinoko_m} skeleton={nodes.polygon39.skeleton} />
        <skinnedMesh name="polygon3b" geometry={nodes.polygon3b.geometry} material={materials.shadow} skeleton={nodes.polygon3b.skeleton} />
        <skinnedMesh name="polygon4" geometry={nodes.polygon4.geometry} material={materials.block3_m} skeleton={nodes.polygon4.skeleton} />
        <skinnedMesh name="polygon5" geometry={nodes.polygon5.geometry} material={materials.a_SAND_m} skeleton={nodes.polygon5.skeleton} />
        <skinnedMesh name="polygon5b" geometry={nodes.polygon5b.geometry} material={materials.shadow} skeleton={nodes.polygon5b.skeleton} />
        <skinnedMesh name="polygon6" geometry={nodes.polygon6.geometry} material={materials.tatemono_m} skeleton={nodes.polygon6.skeleton} />
        <skinnedMesh name="polygon76" geometry={nodes.polygon76.geometry} material={materials.WT_EleArrow_ALL} skeleton={nodes.polygon76.skeleton} />
        <skinnedMesh name="polygon8" geometry={nodes.polygon8.geometry} material={materials.a_MainRoad_m} skeleton={nodes.polygon8.skeleton} />
        <skinnedMesh name="polygon8b" geometry={nodes.polygon8b.geometry} material={materials.shadow} skeleton={nodes.polygon8b.skeleton} />
        <skinnedMesh name="polygon93" geometry={nodes.polygon93.geometry} material={materials.hana_m} skeleton={nodes.polygon93.skeleton} />
        <skinnedMesh name="polygon99" geometry={nodes.polygon99.geometry} material={materials.bc_tree_one_m} skeleton={nodes.polygon99.skeleton} />
      </group>
      <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.beginner_course_1} />
        <skinnedMesh name="COLLIDER_ROAD" geometry={nodes.COLLIDER_ROAD.geometry} material={materials['a_MainRoad_m.001']} skeleton={nodes.COLLIDER_ROAD.skeleton} />
      </group>
      <group name="Armature002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.beginner_course_2} />
        <skinnedMesh name="COLLIDER_WALLS" geometry={nodes.COLLIDER_WALLS.geometry} material={materials['fence.001']} skeleton={nodes.COLLIDER_WALLS.skeleton} />
      </group>
      <mesh name="Icosphere001" castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} />
      <mesh name="Icosphere002" castShadow receiveShadow geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} />
    </group>
  )
}

useGLTF.preload('/LUIGICIRCUIT.glb')
