/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/LuigiCircuit.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useTrimesh } from '@react-three/cannon'

// --- 🔧 REGOLA LA GRANDEZZA QUI ---
// Se è ancora troppo grande, scendi a 0.001
// Se è troppo piccola, sali a 0.005 o 0.01
const trackScale = 0.01

export function LuigiCircuit(props) {
  const { scene } = useGLTF('/LuigiCircuit.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  // Configurazione Fisica (Usa la variabile trackScale!)
  const colliderProps = {
    type: 'Static',
    // rotation: [Math.PI / 2, 0, 0], // <--- CANCELLA O COMMENTA QUESTA RIGA
    rotation: [0, 0, 0], // <--- METTI QUESTA AL SUO POSTO
    scale: [trackScale, trackScale, trackScale],
  }

  // 1. ASFALTO
  useTrimesh(() => ({
    args: [nodes.polygon8.geometry.attributes.position.array, nodes.polygon8.geometry.index.array],
    ...colliderProps,
    friction: 0.02,
  }))

  // 2. FUORI PISTA (Sabbia)
  useTrimesh(() => ({
    args: [nodes.polygon5.geometry.attributes.position.array, nodes.polygon5.geometry.index.array],
    ...colliderProps,
    friction: 0.2,
  }))

  // 3. ERBA
  useTrimesh(() => ({
    args: [nodes.polygon3.geometry.attributes.position.array, nodes.polygon3.geometry.index.array],
    ...colliderProps,
    friction: 0.15,
  }))
  useTrimesh(() => ({
    args: [nodes.polygon2.geometry.attributes.position.array, nodes.polygon2.geometry.index.array],
    ...colliderProps,
    friction: 0.15,
  }))

  // 4. MURI
  useTrimesh(() => ({
    args: [nodes.polygon20.geometry.attributes.position.array, nodes.polygon20.geometry.index.array],
    ...colliderProps,
    restitution: 0.5,
  }))

  // 5. CORDOLI
  useTrimesh(() => ({
    args: [nodes.polygon1.geometry.attributes.position.array, nodes.polygon1.geometry.index.array],
    ...colliderProps,
  }))

  return (
    <group {...props} dispose={null}>
      {/* Applichiamo la stessa scala alla grafica */}
      <group rotation={[Math.PI / 2, 0, 0]} scale={trackScale}>
        <primitive object={nodes.beginner_course} />
        
        {/* Tutte le mesh visive... */}
        <skinnedMesh geometry={nodes.polygon0.geometry} material={materials.ef_dushBoard} skeleton={nodes.polygon0.skeleton} />
        <skinnedMesh geometry={nodes.polygon1.geometry} material={materials.a_bc_enseki_m} skeleton={nodes.polygon1.skeleton} />
        <skinnedMesh geometry={nodes.polygon101.geometry} material={materials.lugcap_m} skeleton={nodes.polygon101.skeleton} />
        <skinnedMesh geometry={nodes.polygon106.geometry} material={materials.bc_spot_m} skeleton={nodes.polygon106.skeleton} />
        <skinnedMesh geometry={nodes.polygon116.geometry} material={materials.lake_m} skeleton={nodes.polygon116.skeleton} />
        <skinnedMesh geometry={nodes.polygon117.geometry} material={materials.yama_m} skeleton={nodes.polygon117.skeleton} />
        <skinnedMesh geometry={nodes.polygon17.geometry} material={materials.bc_kankyaku_m} skeleton={nodes.polygon17.skeleton} />
        <skinnedMesh geometry={nodes.polygon1b.geometry} material={materials.shadow} skeleton={nodes.polygon1b.skeleton} />
        <skinnedMesh geometry={nodes.polygon2.geometry} material={materials.a_kusa_soto} skeleton={nodes.polygon2.skeleton} />
        <skinnedMesh geometry={nodes.polygon20.geometry} material={materials.fence} skeleton={nodes.polygon20.skeleton} />
        <skinnedMesh geometry={nodes.polygon22.geometry} material={materials.popkanban_m} skeleton={nodes.polygon22.skeleton} />
        <skinnedMesh geometry={nodes.polygon23.geometry} material={materials.kusa_kanban_m} skeleton={nodes.polygon23.skeleton} />
        <skinnedMesh geometry={nodes.polygon27.geometry} material={materials.a_bc_kankyakuseat_m} skeleton={nodes.polygon27.skeleton} />
        <skinnedMesh geometry={nodes.polygon27b.geometry} material={materials.shadow} skeleton={nodes.polygon27b.skeleton} />
        <skinnedMesh geometry={nodes.polygon2b.geometry} material={materials.shadow} skeleton={nodes.polygon2b.skeleton} />
        <skinnedMesh geometry={nodes.polygon3.geometry} material={materials.a_kusa_waki_m} skeleton={nodes.polygon3.skeleton} />
        <skinnedMesh geometry={nodes.polygon38.geometry} material={materials.enkei_yama_m} skeleton={nodes.polygon38.skeleton} />
        <skinnedMesh geometry={nodes.polygon39.geometry} material={materials.kinoko_m} skeleton={nodes.polygon39.skeleton} />
        <skinnedMesh geometry={nodes.polygon3b.geometry} material={materials.shadow} skeleton={nodes.polygon3b.skeleton} />
        <skinnedMesh geometry={nodes.polygon4.geometry} material={materials.block3_m} skeleton={nodes.polygon4.skeleton} />
        <skinnedMesh geometry={nodes.polygon5.geometry} material={materials.a_SAND_m} skeleton={nodes.polygon5.skeleton} />
        <skinnedMesh geometry={nodes.polygon5b.geometry} material={materials.shadow} skeleton={nodes.polygon5b.skeleton} />
        <skinnedMesh geometry={nodes.polygon6.geometry} material={materials.tatemono_m} skeleton={nodes.polygon6.skeleton} />
        <skinnedMesh geometry={nodes.polygon76.geometry} material={materials.WT_EleArrow_ALL} skeleton={nodes.polygon76.skeleton} />
        <skinnedMesh geometry={nodes.polygon8.geometry} material={materials.a_MainRoad_m} skeleton={nodes.polygon8.skeleton} />
        <skinnedMesh geometry={nodes.polygon8b.geometry} material={materials.shadow} skeleton={nodes.polygon8b.skeleton} />
        <skinnedMesh geometry={nodes.polygon93.geometry} material={materials.hana_m} skeleton={nodes.polygon93.skeleton} />
        <skinnedMesh geometry={nodes.polygon99.geometry} material={materials.bc_tree_one_m} skeleton={nodes.polygon99.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/LuigiCircuit.glb')