/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/FlameRunner.glb --transform --out src/models/Flame_runner.jsx -r public 
Files: public/FlameRunner.glb [147.64KB] > /home/gpicchio/Desktop/milestone06/prova1/mkwii-THREEJS/mario-kart-react/FlameRunner-transformed.glb [36.38KB] (75%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function FlameRunner(props) {
  const { scene } = useGLTF('/../FlameRunner.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.la_bike_all} />
      <skinnedMesh geometry={nodes.polygon0.geometry} material={materials.mat_body} skeleton={nodes.polygon0.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.polygon1.geometry} material={materials.mat_tire} skeleton={nodes.polygon1.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <skinnedMesh geometry={nodes.polygon2.geometry} material={materials.mat_screen} skeleton={nodes.polygon2.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/../FlameRunner.glb')
