/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Flame_flyer.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function KartModel(props) {
  const { scene } = useGLTF('/Flame_flyer.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.lb_kart_all} />
        <skinnedMesh geometry={nodes.polygon0.geometry} material={materials.mat_tire_rim} skeleton={nodes.polygon0.skeleton} />
        <skinnedMesh geometry={nodes.polygon1.geometry} material={materials.mat_tire} skeleton={nodes.polygon1.skeleton} />
        <skinnedMesh geometry={nodes.polygon2.geometry} material={materials.mat_body} skeleton={nodes.polygon2.skeleton} />
        <skinnedMesh geometry={nodes.polygon3.geometry} material={materials.mat_screen} skeleton={nodes.polygon3.skeleton} />
        <skinnedMesh geometry={nodes.polygon4.geometry} material={materials.mat_engine} skeleton={nodes.polygon4.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Flame_flyer.glb')
