/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// https://models.spriters-resource.com/wii/mkwii/

import React, { useRef, useEffect } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { MathUtils } from 'three'
import { DoubleSide } from 'three'

export function FunkyKong({ steer, drift, ...props }) {
  const { scene } = useGLTF('/funky_kong.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  useEffect(() => {
    // Attraversa tutto il modello e forza il rendering doppio lato
    scene.traverse((object) => {
      if (object.isMesh) {
        object.material.side = DoubleSide // Disegna fronte e retro
        object.castShadow = true          // Già che ci siamo, attiviamo le ombre
        object.receiveShadow = true
        
        // Fix opzionale per la trasparenza (se sembra vetro)
        object.material.transparent = false 
        object.material.depthWrite = true
      }
    })
  }, [scene])

  useFrame((state, delta) => {
    let targetLean = -steer * 0.5
    if (drift !== 0) {
        targetLean = drift === 1 ? -0.8 : 0.8
    }
    if (nodes.funky_body) {
        nodes.funky_body.rotation.y = MathUtils.damp(nodes.funky_body.rotation.y, targetLean, 4, delta)

    }
  })

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.funky_body} />
        <skinnedMesh 
            geometry={nodes.polygon0.geometry} 
            material={materials.funky_all_tx} 
            skeleton={nodes.polygon0.skeleton} 
        />
      </group>
    </group>
  )
}

useGLTF.preload('/funky_kong.glb')