/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Mario.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { MathUtils } from 'three'
import { DoubleSide } from 'three'

export function Mario({ steer, drift, ...props }) {
  const { scene } = useGLTF('/Mario.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  useEffect(() => {
    // Attraversa tutto il modello e forza il rendering doppio lato
    scene.traverse((object) => {
      if (object.isMesh) {
        object.material.side = DoubleSide // Disegna fronte e retro
        object.castShadow = true          // Già che ci siamo, attiviamo le ombre
        object.receiveShadow = true
        
        // Fix opzionale per la trasparenza (se sembra vetro)
        object.material.transparent = false 
        object.material.depthWrite = true
      }
    })
  }, [scene])

  useFrame((state, delta) => {
    let targetLean = -steer * 0.5
    if (drift !== 0) {
      targetLean = drift === 1 ? -0.8 : 0.8
    }
    if (nodes.mario_body) {
      nodes.mario_body.rotation.y = MathUtils.damp(nodes.mario_body.rotation.y, targetLean, 4, delta)
    }
  })

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mario_body} />
        <skinnedMesh geometry={nodes.polygon0.geometry} material={materials.mario_all_tx} skeleton={nodes.polygon0.skeleton} />
        <skinnedMesh geometry={nodes.polygon1.geometry} material={materials.mario_eye_tx} skeleton={nodes.polygon1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mario.glb')
