/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/StandardKartM.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function StandardKartM(props) {
  const { scene } = useGLTF('/StandardKartM.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mdf_kart_all} />
        <skinnedMesh geometry={nodes.polygon0.geometry} material={materials.mat_tire_rim} skeleton={nodes.polygon0.skeleton} />
        <skinnedMesh geometry={nodes.polygon1.geometry} material={materials['mat_tire.001']} skeleton={nodes.polygon1.skeleton} />
        <skinnedMesh geometry={nodes.polygon2.geometry} material={materials['mat_body.001']} skeleton={nodes.polygon2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/StandardKartM.glb')
